swagger: '2.0'
info:
  version: 1.0.0
  title: Member Service API
  description: Service to handle Members
  contact:
    email: to@adheteguh.com
    
paths:
  
  /orgs/{organizationName}/members:
    get:
      tags:
        - member
      operationId: getMembers
      summary: Get All Members
      description: Get All Members
      produces:
        - application/json
      parameters:
        - in: path
          name: organizationName
          type: string
          required: true
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/responseMember"
        400:
          description: Bad Request / Validation exception
          schema:
            $ref: '#/definitions/error400'
        404:
          description: Resource Not Found
          schema:
            $ref: '#/definitions/error404'
        default:
          description: Error
          schema:
            $ref: '#/definitions/errorDefault'
            
definitions:
  responseMember:
    type: object
    properties:
      id:
        type: string
        readOnly: true
        example: aec2b69e-7e98-418a-9889-889be9df628a
      login:
          type: string
          example: johndoe
      organizationName:
        type: string
        example: xendit
      avatarUrl:
        type: string
        example: https://avatar-url.com/example.jpg
      followers:
        type: integer
        example: 99
      following:
        type: integer
        example: 1
      createdAt: 
        type: string
        format: "date-time"
        example: '2020-10-13T23:34:38Z'
        readOnly: true

  error400:
    type: object
    properties:
      code:
        type: string
        example: REQUIRED
      message:
        type: string
        example: Bad Request - Your request is missing parameters. Please verify and resubmit

  error404:
    type: object
    properties:
      message:
        type: string
        example: Resource Not Found 

  errorDefault:
    type: object
    properties:
      code:
        type: string
        example: INTERNAL_SERVER_ERROR
      message:
        type: string
        example: Sorry, an unexpected error has occurred

