version: '3'
services:
  mongo:
    image: mongo:4.2

  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_NAME: db-test